# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm audit


workflows:
  npm-react-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
